
  - name: install PXC 8 deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - percona-xtradb-cluster-full
      - percona-xtrabackup-80
      - percona-toolkit
    when: ansible_os_family == "Debian"
