  - name: Run the equivalent of "apt-get clean" as a separate step
    apt:
      autoclean: true

  - name: Run APT Update
    apt:
      update_cache: yes

  - name: install PXC 8 deb packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - percona-xtradb-cluster-full
      - percona-xtrabackup-80
      - percona-toolkit
    when: ansible_os_family == "Debian"
