  - name: Run the equivalent of "apt-get clean" as a separate step
    apt:
      autoclean: true

  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
      
  - name: install PXC 5.7 previous deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - percona-xtradb-cluster-full-57
      - percona-xtradb-cluster-57
    when: ansible_os_family == "Debian"
