  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
      
  - name: install PXC 8 deb packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - percona-xtradb-cluster-full
      - percona-xtrabackup-80
      - percona-toolkit
    when: ansible_os_family == "Debian"
