  - name: install PXC 5.7 previous deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - percona-xtradb-cluster-full-57
      - percona-xtradb-cluster-57
    when: ansible_os_family == "Debian"
